#!/bin/bash

########################
#
# Help installing the Raspberry Pi kernel
# Usage:
#   ./install
#
# By default this looks for the SD card at /Volumes/UNTITLED and installs the kernel.img from the current directory.
# If you have fswatch installed it will wait untill /Volumes/UNTITLED is found.
# When you're done it will unmount the SD card.
#
#  Options
#   -c Perform a clean and build before install
#   -b Perform a build before install
#   -m Keeps the SD card mounted after install
#
########################

INSTALL_DIR="/Volumes/UNTITLED"
CURRENT_DIR=$(pwd)
KERN_FILE_NAME="kernel.img"

CLEAN=0
BUILD=0
KEEP_MOUNTED=0
HELP=0

while getopts 'cbm' flag; do
  case "${flag}" in
    c) CLEAN=1 ;;
    b) BUILD=1 ;;
    m) KEEP_MOUNTED=1 ;;
    h) HELP=1 ;;
    *) HELP=1 ;;
  esac
done

if [ $HELP -eq 1 ]; then
  echo "$(basename "$0") [-h] [-c b m] -- Installs the Raspberry Pi OS to the SD card mounted at $INSTALL_DIR
  where:
    -h : Show this help text
    -c : Perform a clean then build
    -b : Perform a build
    -m : Keep the SD card mounted after install
"
  exit 1
fi

if [ $CLEAN -eq 1 ]; then
  BUILD=1
  echo "Cleaning..."
  make clean
fi

if [ $BUILD -eq 1 ]; then
  echo "Building..."
  make
fi

if [[ ! -d "$INSTALL_DIR" ]]; then
  echo "Can't find install location $INSTALL_DIR"
  # If fswatch is installed wait for the install dir to be mounted
  # run `brew install fswatch`
  if hash fswatch 2>/dev/null; then
    echo "Please insert SD card..."
    fswatch "$INSTALL_DIR" | exit 0
    if [[ ! -d "$INSTALL_DIR" ]]; then
      exit 1
    fi
  else
    exit 1
  fi
fi
if [[ ! -e "$CURRENT_DIR/$KERN_FILE_NAME" ]]; then
  echo "No '$KERN_FILE_NAME'  Building..."
  make clean
  make
fi

if [ -e "$INSTALL_DIR/$KERN_FILE_NAME" ]; then
  echo "Removing $KERN_FILE_NAME from $INSTALL_DIR"
  rm -f "$INSTALL_DIR/$KERN_FILE_NAME"
fi

echo "Copying $CURRENT_DIR/$KERN_FILE_NAME to $INSTALL_DIR/$KERN_FILE_NAME"
cp "$CURRENT_DIR/$KERN_FILE_NAME" "$INSTALL_DIR/$KERN_FILE_NAME"

if [ $KEEP_MOUNTED -eq 0 ]; then
  echo "Unmounting $INSTALL_DIR"
  diskutil unmount "$INSTALL_DIR"
fi
